// REAL implementation of SigilApi over @microsoft/power-apps.
//
// The Custom API calls go through the TYPED CLIENTS generated by
// `power-apps add-dataverse-api sanic_sigil_capi_*` (src/generated/, doc 05 §2 — autogenerated,
// do NOT edit by hand). Each generated service exposes one static method whose positional
// parameters mirror the Custom API's request parameters; it returns an IOperationResult
// ({ success, data, error }). Table reads go through the Dataverse connector
// (MicrosoftDataverseService.ListRecords) — implemented in a follow-up (still PENDING_DATASOURCE).

import type {
  CreateTransactionInput,
  UpdateDraftInput,
  GetDocumentContentInput,
  RejectTransactionInput,
  CancelTransactionInput,
  ValidateMasterSignatureOutput,
  GetMasterSignatureOutput,
  VerifyDocumentInput,
  VerifyDocumentOutput,
} from './contracts';
import type {
  SigilApi,
  TransactionView,
  ParticipantView,
  EventView,
  ZoneView,
  UserSummary,
  MasterSignatureVersion,
} from './SigilApi';
import {
  Sanic_sigil_capi_CreateTransactionService,
  Sanic_sigil_capi_UpdateDraftService,
  Sanic_sigil_capi_DeleteDraftService,
  Sanic_sigil_capi_SendTransactionService,
  Sanic_sigil_capi_SubmitSignatureService,
  Sanic_sigil_capi_RejectTransactionService,
  Sanic_sigil_capi_CancelTransactionService,
  Sanic_sigil_capi_RetrySealingService,
  Sanic_sigil_capi_GetDocumentContentService,
  Sanic_sigil_capi_ValidateMasterSignatureService,
  Sanic_sigil_capi_GetMasterSignatureService,
  Sanic_sigil_capi_GetMasterSignatureHistoryService,
  Sanic_sigil_capi_VerifyDocumentService,
} from '../generated';

/** Unwraps a generated IOperationResult: returns the response body, or throws on failure. */
function ok(result: { success: boolean; data: unknown; error?: unknown }): unknown {
  if (!result.success) {
    throw result.error instanceof Error ? result.error : new Error('Dataverse operation failed.');
  }
  return result.data;
}

export class PowerAppsSigilApi implements SigilApi {
  // Identity is NOT taken from here: the app shell resolves getContext() (async) ONCE at
  // startup and provides it via PowerProvider (doc 05 §9 — never authoritative). This method
  // exists for the seam contract; in production the UI uses the React context.
  currentUser() {
    return {};
  }

  // People picker: a systemuser datasource search (implemented with the reads, below).
  async searchUsers(_query: string): Promise<UserSummary[]> {
    throw new Error(PENDING_DATASOURCE);
  }

  async validateMasterSignature(imageBase64: string): Promise<ValidateMasterSignatureOutput> {
    return ok(
      await Sanic_sigil_capi_ValidateMasterSignatureService.sanic_sigil_capi_ValidateMasterSignature(imageBase64),
    ) as ValidateMasterSignatureOutput;
  }
  async getMasterSignature(): Promise<GetMasterSignatureOutput> {
    return ok(
      await Sanic_sigil_capi_GetMasterSignatureService.sanic_sigil_capi_GetMasterSignature(),
    ) as GetMasterSignatureOutput;
  }
  async getMasterSignatureHistory(): Promise<MasterSignatureVersion[]> {
    const d = ok(
      await Sanic_sigil_capi_GetMasterSignatureHistoryService.sanic_sigil_capi_GetMasterSignatureHistory(),
    ) as { HistoryJson: string };
    return JSON.parse(d.HistoryJson) as MasterSignatureVersion[];
  }
  async createTransaction(input: CreateTransactionInput): Promise<string> {
    const d = ok(
      await Sanic_sigil_capi_CreateTransactionService.sanic_sigil_capi_CreateTransaction(
        input.Name, input.RoutingType, input.PdfBase64, input.ParticipantsJson,
        input.Message, input.ExpirationDays, input.ZonesJson,
      ),
    ) as { TransactionId: string };
    return d.TransactionId;
  }
  async updateDraft(input: UpdateDraftInput): Promise<void> {
    ok(
      await Sanic_sigil_capi_UpdateDraftService.sanic_sigil_capi_UpdateDraft(
        input.Target, input.Name, input.Message, input.RoutingType,
        input.ExpirationDays, input.PdfBase64, input.ParticipantsJson, input.ZonesJson,
      ),
    );
  }
  async deleteDraft(txId: string): Promise<void> {
    ok(await Sanic_sigil_capi_DeleteDraftService.sanic_sigil_capi_DeleteDraft(txId));
  }
  async sendTransaction(txId: string): Promise<void> {
    ok(await Sanic_sigil_capi_SendTransactionService.sanic_sigil_capi_SendTransaction(txId));
  }
  async submitSignature(txId: string): Promise<boolean> {
    const d = ok(
      await Sanic_sigil_capi_SubmitSignatureService.sanic_sigil_capi_SubmitSignature(txId),
    ) as { IsLastSigner: boolean };
    return d.IsLastSigner;
  }
  async rejectTransaction(input: RejectTransactionInput): Promise<void> {
    ok(await Sanic_sigil_capi_RejectTransactionService.sanic_sigil_capi_RejectTransaction(input.Target, input.Reason));
  }
  async cancelTransaction(input: CancelTransactionInput): Promise<void> {
    ok(await Sanic_sigil_capi_CancelTransactionService.sanic_sigil_capi_CancelTransaction(input.Target, input.Reason));
  }
  async retrySealing(txId: string): Promise<void> {
    ok(await Sanic_sigil_capi_RetrySealingService.sanic_sigil_capi_RetrySealing(txId));
  }
  async getDocumentContent(input: GetDocumentContentInput): Promise<string> {
    const d = ok(
      await Sanic_sigil_capi_GetDocumentContentService.sanic_sigil_capi_GetDocumentContent(input.Target, input.DocumentType),
    ) as { PdfBase64: string };
    return d.PdfBase64;
  }
  async verifyDocument(input: VerifyDocumentInput): Promise<VerifyDocumentOutput> {
    return ok(
      await Sanic_sigil_capi_VerifyDocumentService.sanic_sigil_capi_VerifyDocument(input.TransactionId, input.Sha256Hash),
    ) as VerifyDocumentOutput;
  }

  // ── Table reads: go through the Dataverse connector (MicrosoftDataverseService.ListRecords,
  //    doc 05 §1). Implemented in the reads follow-up; until then MockSigilApi covers dev. ──
  async myPending(): Promise<{ tx: TransactionView; participant: ParticipantView }[]> {
    throw new Error(PENDING_DATASOURCE);
  }
  async myRequests(): Promise<TransactionView[]> {
    throw new Error(PENDING_DATASOURCE);
  }
  async myParticipations(): Promise<TransactionView[]> {
    throw new Error(PENDING_DATASOURCE);
  }
  async getTransaction(_txId: string): Promise<TransactionView | undefined> {
    throw new Error(PENDING_DATASOURCE);
  }
  async participantsOf(_txId: string): Promise<ParticipantView[]> {
    throw new Error(PENDING_DATASOURCE);
  }
  async zonesOf(_txId: string): Promise<ZoneView[]> {
    throw new Error(PENDING_DATASOURCE);
  }
  async eventsOf(_txId: string): Promise<EventView[]> {
    throw new Error(PENDING_DATASOURCE);
  }
}

const PENDING_DATASOURCE =
  'Tabular reads are not wired yet (MicrosoftDataverseService.ListRecords). The app uses MockSigilApi until then.';
