// REAL implementation of SigilApi over @microsoft/power-apps.
//
// Custom API calls → the TYPED CLIENTS generated by `power-apps add-dataverse-api` (src/generated/,
// autogenerated, do NOT edit). Each service exposes one static method whose positional parameters
// mirror the Custom API's request parameters and returns an IOperationResult ({ success, data, error }).
// Table reads → the Dataverse connector (MicrosoftDataverseService.ListRecords) with $filter or a
// FetchXML that uses `eq-userid` (server-side current user) so we don't resolve identity client-side.
//
// ⚠️ FIRST INTEGRATION PASS: the read mappings assume the standard entity-set names (logical name +
// "s") and Dataverse response shape (lookups as `_<attr>_value`, option sets as numbers, formatted
// values via the include-annotations prefer). Verify end-to-end with `power-apps run` against Dev.

import type {
  CreateTransactionInput,
  UpdateDraftInput,
  GetDocumentContentInput,
  RejectTransactionInput,
  CancelTransactionInput,
  ValidateMasterSignatureOutput,
  GetMasterSignatureOutput,
  VerifyDocumentInput,
  VerifyDocumentOutput,
} from './contracts';
import type {
  SigilApi,
  TransactionView,
  ParticipantView,
  EventView,
  ZoneView,
  UserSummary,
  MasterSignatureVersion,
  DocumentRow,
  DocumentQuery,
  DocumentPage,
  TransactionPage,
  PendingPage,
} from './SigilApi';
import { getClient } from '@microsoft/power-apps/data';
import { getContext } from '@microsoft/power-apps/app';
import { dataSourcesInfo } from '../../.power/schemas/appschemas/dataSourcesInfo';
import { dataverseFaultMessage } from './faults';
import {
  Sanic_sigil_capi_CreateTransactionService,
  Sanic_sigil_capi_UpdateDraftService,
  Sanic_sigil_capi_DeleteDraftService,
  Sanic_sigil_capi_SendTransactionService,
  Sanic_sigil_capi_SubmitSignatureService,
  Sanic_sigil_capi_RejectTransactionService,
  Sanic_sigil_capi_CancelTransactionService,
  Sanic_sigil_capi_RetrySealingService,
  Sanic_sigil_capi_GetDocumentContentService,
  Sanic_sigil_capi_ValidateMasterSignatureService,
  Sanic_sigil_capi_GetMasterSignatureService,
  Sanic_sigil_capi_GetMasterSignatureHistoryService,
  Sanic_sigil_capi_VerifyDocumentService,
  Sanic_sigil_capi_SearchDocumentsService,
} from '../generated';

// The Dataverse data client (retrieveMultipleRecordsAsync/retrieveRecordAsync). NOT the low-level
// connector ListRecords — that path returns "Invalid organization URL 'null'" in local mode.
const dv = getClient(dataSourcesInfo);
// Table ENTITY-SET names (plural). The SDK's dataverse executor puts this string DIRECTLY into the
// OData path (`api/data/v9.0/<name>`) AND uses it as the data-source lookup key in both
// dataSourcesInfo.ts and the runtime databaseReferences — so it MUST be the entity set, not the
// singular logical name. Column/attribute names elsewhere stay logical.
const T = {
  tx: 'sanic_sigil_tbl_transactions',
  participant: 'sanic_sigil_tbl_participants',
  zone: 'sanic_sigil_tbl_signaturezones',
  event: 'sanic_sigil_tbl_events',
  user: 'systemusers',
} as const;

/** Unwraps a generated IOperationResult: returns the response body, or throws on failure. */
function ok(result: { success: boolean; data: unknown; error?: unknown }): unknown {
  if (!result.success) {
    // The fault arrives in varied shapes (plain object, Error, or a JSON string inside .message).
    // Extract the innermost readable message so callers can show/log the actual cause instead of
    // a raw JSON blob or a generic string.
    throw new Error(dataverseFaultMessage(result.error));
  }
  return result.data;
}

// ── Schema (doc 12). Primary keys = logical name + "id"; lookups read as `_<attr>_value`. ──
const COL = {
  txId: 'sanic_sigil_tbl_transactionid',
  partId: 'sanic_sigil_tbl_participantid',
  zoneId: 'sanic_sigil_tbl_signaturezoneid',
  eventId: 'sanic_sigil_tbl_eventid',
  name: 'sanic_sigil_name',
  status: 'sanic_sigil_status',
  routing: 'sanic_sigil_routingtype',
  message: 'sanic_sigil_message',
  sentOn: 'sanic_sigil_senton',
  expiresOn: 'sanic_sigil_expireson',
  completedOn: 'sanic_sigil_completedon',
  pTransactionId: 'sanic_sigil_transactionid', // participant/event → transaction lookup
  pUserId: 'sanic_sigil_userid',
  pOrder: 'sanic_sigil_order',
  pTurnActivatedOn: 'sanic_sigil_turnactivatedon',
  pSignedOn: 'sanic_sigil_signedon',
  pSignerName: 'sanic_sigil_signername',
  pSignerEmail: 'sanic_sigil_signeremail',
  zParticipantId: 'sanic_sigil_participantid',
  zPage: 'sanic_sigil_page',
  zPosX: 'sanic_sigil_posx',
  zPosY: 'sanic_sigil_posy',
  zWidth: 'sanic_sigil_width',
  zHeight: 'sanic_sigil_height',
  eType: 'sanic_sigil_type',
  eActorName: 'sanic_sigil_actorname',
  eOccurredOn: 'sanic_sigil_occurredon',
  eDetails: 'sanic_sigil_details',
  owner: '_ownerid_value',
} as const;

const DASH_PAGE_SIZE = 25; // dashboard infinite-scroll page size
const PARTICIPANT_ACTIVE_TURN = 159460001;
const TX_PENDING = 159460001;
const TX_PARTIALLY_SIGNED = 159460002;
const ROUTING_SEQUENTIAL = 159460000;

type Row = Record<string, unknown>;
const s = (r: Row, k: string): string | undefined => (r[k] == null ? undefined : String(r[k]));
const n = (r: Row, k: string): number | undefined => (r[k] == null ? undefined : Number(r[k]));
const fmt = (r: Row, k: string): string | undefined => s(r, `${k}@OData.Community.Display.V1.FormattedValue`);
const lookup = (r: Row, attr: string): string | undefined => s(r, `_${attr}_value`);
const esc = (v: string): string => v.replace(/'/g, "''"); // OData string literal escaping

function txView(r: Row): TransactionView {
  return {
    id: s(r, COL.txId) ?? '',
    name: s(r, COL.name) ?? '',
    state: n(r, COL.status) ?? 0,
    routing: n(r, COL.routing) === ROUTING_SEQUENTIAL ? 'sequential' : 'parallel',
    creatorId: s(r, COL.owner) ?? '',
    creatorName: fmt(r, 'ownerid'),
    message: s(r, COL.message),
    sentOn: s(r, COL.sentOn),
    expiresOn: s(r, COL.expiresOn),
    completedOn: s(r, COL.completedOn),
  };
}
function partView(r: Row): ParticipantView {
  return {
    id: s(r, COL.partId) ?? '',
    userId: lookup(r, COL.pUserId) ?? '',
    name: s(r, COL.pSignerName) ?? fmt(r, COL.pUserId),
    email: s(r, COL.pSignerEmail),
    order: n(r, COL.pOrder),
    state: n(r, COL.status) ?? 0,
    signedOn: s(r, COL.pSignedOn),
    turnActivatedOn: s(r, COL.pTurnActivatedOn),
  };
}
function eventView(r: Row): EventView {
  return {
    id: s(r, COL.eventId) ?? '',
    type: n(r, COL.eType) ?? 0,
    actorName: s(r, COL.eActorName),
    occurredOn: s(r, COL.eOccurredOn) ?? s(r, 'createdon') ?? '',
    details: s(r, COL.eDetails),
  };
}
function zoneView(r: Row): ZoneView {
  return {
    id: s(r, COL.zoneId) ?? '',
    participantId: lookup(r, COL.zParticipantId) ?? '',
    page: n(r, COL.zPage) ?? 1,
    x: n(r, COL.zPosX) ?? 0,
    y: n(r, COL.zPosY) ?? 0,
    w: n(r, COL.zWidth) ?? 0,
    h: n(r, COL.zHeight) ?? 0,
  };
}
function userView(r: Row): UserSummary {
  return { id: s(r, 'systemuserid') ?? '', name: s(r, 'fullname') ?? '', email: s(r, 'internalemailaddress') };
}

// A row from SearchDocuments.ResultsJson (already enriched server-side). state/routing arrive as the
// raw choice ints; dates as ISO strings or null.
interface RawDoc {
  id: string; name: string; state: number; routing: number;
  creatorId?: string; creatorName?: string; message?: string | null;
  sentOn?: string | null; expiresOn?: string | null; completedOn?: string | null; createdOn?: string | null;
  mySignatureVersion?: number | null;
  participants?: { userId: string; name: string }[];
}
function mapRawDoc(r: RawDoc): DocumentRow {
  const row: DocumentRow = {
    id: r.id,
    name: r.name,
    state: r.state,
    routing: r.routing === ROUTING_SEQUENTIAL ? 'sequential' : 'parallel',
    creatorId: r.creatorId ?? '',
    participants: r.participants ?? [],
  };
  if (r.creatorName) row.creatorName = r.creatorName;
  if (r.message) row.message = r.message;
  if (r.sentOn) row.sentOn = r.sentOn;
  if (r.expiresOn) row.expiresOn = r.expiresOn;
  if (r.completedOn) row.completedOn = r.completedOn;
  if (r.createdOn) row.createdOn = r.createdOn;
  if (r.mySignatureVersion != null) row.mySignatureVersion = r.mySignatureVersion;
  return row;
}

export class PowerAppsSigilApi implements SigilApi {
  // Identity is NOT taken from here: the app shell resolves getContext() (async) ONCE at startup and
  // provides it via PowerProvider (doc 05 §9). This exists for the seam contract only.
  currentUser() {
    return {};
  }
  // Resolves the caller's Dataverse systemuserid (from the Entra objectId in getContext()), cached.
  // Screens use this to match the caller against participant.userId — currentUser() can't in real mode.
  async getCurrentUserId(): Promise<string> {
    return this.me();
  }

  // ── Custom API actions ──
  // Persist=false → validate only (preview). The UI confirms before replacing the active signature.
  async validateMasterSignature(imageBase64: string): Promise<ValidateMasterSignatureOutput> {
    return ok(
      await Sanic_sigil_capi_ValidateMasterSignatureService.sanic_sigil_capi_ValidateMasterSignature(imageBase64, false),
    ) as ValidateMasterSignatureOutput;
  }
  // Persist=true → validate again server-side AND commit the new active version (irreversible).
  async saveMasterSignature(imageBase64: string): Promise<ValidateMasterSignatureOutput> {
    return ok(
      await Sanic_sigil_capi_ValidateMasterSignatureService.sanic_sigil_capi_ValidateMasterSignature(imageBase64, true),
    ) as ValidateMasterSignatureOutput;
  }
  async getMasterSignature(): Promise<GetMasterSignatureOutput> {
    return ok(
      await Sanic_sigil_capi_GetMasterSignatureService.sanic_sigil_capi_GetMasterSignature(),
    ) as GetMasterSignatureOutput;
  }
  async getMasterSignatureHistory(): Promise<MasterSignatureVersion[]> {
    const d = ok(
      await Sanic_sigil_capi_GetMasterSignatureHistoryService.sanic_sigil_capi_GetMasterSignatureHistory(),
    ) as { HistoryJson: string };
    const raw = JSON.parse(d.HistoryJson) as Array<Partial<MasterSignatureVersion>>;
    // Tolerate older backends that don't send `documents` yet (default to []).
    return raw.map((v) => ({ ...v, documents: v.documents ?? [] })) as MasterSignatureVersion[];
  }
  async createTransaction(input: CreateTransactionInput): Promise<string> {
    const d = ok(
      await Sanic_sigil_capi_CreateTransactionService.sanic_sigil_capi_CreateTransaction(
        input.Name, input.RoutingType, input.PdfBase64, input.ParticipantsJson,
        input.Message, input.ExpirationDays, input.ZonesJson,
      ),
    ) as { TransactionId: string };
    return d.TransactionId;
  }
  async updateDraft(input: UpdateDraftInput): Promise<void> {
    ok(
      await Sanic_sigil_capi_UpdateDraftService.sanic_sigil_capi_UpdateDraft(
        input.Target, input.Name, input.Message, input.RoutingType,
        input.ExpirationDays, input.PdfBase64, input.ParticipantsJson, input.ZonesJson,
      ),
    );
  }
  async deleteDraft(txId: string): Promise<void> {
    ok(await Sanic_sigil_capi_DeleteDraftService.sanic_sigil_capi_DeleteDraft(txId));
  }
  async sendTransaction(txId: string): Promise<void> {
    ok(await Sanic_sigil_capi_SendTransactionService.sanic_sigil_capi_SendTransaction(txId));
  }
  async submitSignature(txId: string): Promise<boolean> {
    const d = ok(
      await Sanic_sigil_capi_SubmitSignatureService.sanic_sigil_capi_SubmitSignature(txId),
    ) as { IsLastSigner: boolean };
    return d.IsLastSigner;
  }
  async rejectTransaction(input: RejectTransactionInput): Promise<void> {
    ok(await Sanic_sigil_capi_RejectTransactionService.sanic_sigil_capi_RejectTransaction(input.Target, input.Reason));
  }
  async cancelTransaction(input: CancelTransactionInput): Promise<void> {
    ok(await Sanic_sigil_capi_CancelTransactionService.sanic_sigil_capi_CancelTransaction(input.Target, input.Reason));
  }
  async retrySealing(txId: string): Promise<void> {
    ok(await Sanic_sigil_capi_RetrySealingService.sanic_sigil_capi_RetrySealing(txId));
  }
  async getDocumentContent(input: GetDocumentContentInput): Promise<string> {
    const d = ok(
      await Sanic_sigil_capi_GetDocumentContentService.sanic_sigil_capi_GetDocumentContent(input.Target, input.DocumentType),
    ) as { PdfBase64: string };
    return d.PdfBase64;
  }
  async verifyDocument(input: VerifyDocumentInput): Promise<VerifyDocumentOutput> {
    return ok(
      await Sanic_sigil_capi_VerifyDocumentService.sanic_sigil_capi_VerifyDocument(input.TransactionId, input.Sha256Hash),
    ) as VerifyDocumentOutput;
  }

  // ── Table reads (Dataverse data client — retrieveMultipleRecordsAsync, NOT the connector) ──
  // The connection runs as the Service Principal (no per-user security trimming), so reads filter
  // EXPLICITLY by the caller's systemuserid — resolved once from getContext() (Entra objectId) and cached.
  private meId: string | undefined;
  private async me(): Promise<string> {
    if (this.meId !== undefined) return this.meId;
    const ctx = await getContext();
    const oid = ctx.user?.objectId;
    const upn = ctx.user?.userPrincipalName;
    const filter = oid
      ? `azureactivedirectoryobjectid eq ${oid}`
      : `internalemailaddress eq '${esc(upn ?? '')}'`;
    const rows = ok(await dv.retrieveMultipleRecordsAsync<Row>(T.user, { filter, select: ['systemuserid'], top: 1 })) as Row[];
    this.meId = s(rows[0] ?? {}, 'systemuserid') ?? '';
    return this.meId;
  }

  async searchUsers(query: string): Promise<UserSummary[]> {
    const q = query.trim();
    const base = 'isdisabled eq false';
    const filter = q
      ? `(contains(fullname,'${esc(q)}') or contains(internalemailaddress,'${esc(q)}')) and ${base}`
      : base;
    const rows = ok(await dv.retrieveMultipleRecordsAsync<Row>(T.user, {
      select: ['systemuserid', 'fullname', 'internalemailaddress'], filter, orderBy: ['fullname asc'], top: 20,
    })) as Row[];
    return rows.map(userView);
  }

  async myRequests(): Promise<TransactionView[]> {
    const rows = ok(await dv.retrieveMultipleRecordsAsync<Row>(T.tx, {
      filter: `${COL.owner} eq ${await this.me()}`, orderBy: ['createdon desc'],
    })) as Row[];
    return rows.map(txView);
  }

  async myParticipations(): Promise<TransactionView[]> {
    const parts = ok(await dv.retrieveMultipleRecordsAsync<Row>(T.participant, {
      filter: `_${COL.pUserId}_value eq ${await this.me()}`, select: [`_${COL.pTransactionId}_value`],
    })) as Row[];
    const txIds = [...new Set(parts.map((p) => lookup(p, COL.pTransactionId)).filter(Boolean) as string[])];
    if (!txIds.length) return [];
    const filter = txIds.map((id) => `${COL.txId} eq ${id}`).join(' or ');
    const rows = ok(await dv.retrieveMultipleRecordsAsync<Row>(T.tx, { filter, orderBy: ['createdon desc'] })) as Row[];
    return rows.map(txView);
  }

  // Paged variants (recent-first) for the dashboard's infinite scroll. `ok()` can't be used here
  // because we also need the result's continuation token (skipToken), so faults are handled inline.
  async myRequestsPage(cookie?: string): Promise<TransactionPage> {
    const opts: { filter: string; orderBy: string[]; maxPageSize: number; skipToken?: string } = {
      filter: `${COL.owner} eq ${await this.me()}`, orderBy: ['createdon desc'], maxPageSize: DASH_PAGE_SIZE,
    };
    if (cookie) opts.skipToken = cookie;
    const res = await dv.retrieveMultipleRecordsAsync<Row>(T.tx, opts);
    if (!res.success) throw new Error(dataverseFaultMessage(res.error));
    return { rows: (res.data as Row[]).map(txView), nextCookie: res.skipToken ?? '' };
  }

  async myParticipationsPage(cookie?: string, status?: number): Promise<TransactionPage> {
    const opts: { filter: string; select: string[]; orderBy: string[]; maxPageSize: number; skipToken?: string } = {
      filter: `_${COL.pUserId}_value eq ${await this.me()}`, select: [`_${COL.pTransactionId}_value`],
      orderBy: ['createdon desc'], maxPageSize: DASH_PAGE_SIZE,
    };
    if (cookie) opts.skipToken = cookie;
    const res = await dv.retrieveMultipleRecordsAsync<Row>(T.participant, opts);
    if (!res.success) throw new Error(dataverseFaultMessage(res.error));
    const nextCookie = res.skipToken ?? '';
    const txIds = [...new Set((res.data as Row[]).map((p) => lookup(p, COL.pTransactionId)).filter(Boolean) as string[])];
    if (!txIds.length) return { rows: [], nextCookie };
    // Status filter (e.g. completed-only) is applied server-side on the tx fetch.
    const idFilter = `(${txIds.map((id) => `${COL.txId} eq ${id}`).join(' or ')})`;
    const filter = status != null ? `${idFilter} and ${COL.status} eq ${status}` : idFilter;
    const txRows = ok(await dv.retrieveMultipleRecordsAsync<Row>(T.tx, { filter })) as Row[];
    // Preserve the participant order (recent-first) — the tx `or` filter doesn't guarantee order.
    const byId = new Map(txRows.map((r) => [s(r, COL.txId) ?? '', r]));
    const ordered = txIds.map((id) => byId.get(id)).filter((r): r is Row => !!r);
    return { rows: await this.withCreatorNames(ordered), nextCookie };
  }

  async myPendingPage(cookie?: string): Promise<PendingPage> {
    const opts: { filter: string; orderBy: string[]; maxPageSize: number; skipToken?: string } = {
      filter: `_${COL.pUserId}_value eq ${await this.me()} and ${COL.status} eq ${PARTICIPANT_ACTIVE_TURN}`,
      orderBy: ['createdon desc'], maxPageSize: DASH_PAGE_SIZE,
    };
    if (cookie) opts.skipToken = cookie;
    const res = await dv.retrieveMultipleRecordsAsync<Row>(T.participant, opts);
    if (!res.success) throw new Error(dataverseFaultMessage(res.error));
    const nextCookie = res.skipToken ?? '';
    const parts = res.data as Row[];
    const txIds = [...new Set(parts.map((p) => lookup(p, COL.pTransactionId)).filter(Boolean) as string[])];
    if (!txIds.length) return { rows: [], nextCookie };
    const txRows = ok(await dv.retrieveMultipleRecordsAsync<Row>(T.tx, {
      filter: txIds.map((id) => `${COL.txId} eq ${id}`).join(' or '),
    })) as Row[];
    const viewById = new Map((await this.withCreatorNames(txRows)).map((v) => [v.id, v]));
    // Keep only docs still awaiting signature, in the participant (recent-first) order.
    const rows = parts.flatMap((pr) => {
      const tx = viewById.get(lookup(pr, COL.pTransactionId) ?? '');
      return tx && (tx.state === TX_PENDING || tx.state === TX_PARTIALLY_SIGNED)
        ? [{ tx, participant: partView(pr) }] : [];
    });
    return { rows, nextCookie };
  }

  // Resolve creator display names from systemusers (the owner FormattedValue isn't reliably present
  // on these reads, so "Sent by X" would otherwise be blank). One extra query per page.
  private async withCreatorNames(rows: Row[]): Promise<TransactionView[]> {
    const views = rows.map(txView);
    const ids = [...new Set(views.map((v) => v.creatorId).filter(Boolean))];
    if (!ids.length) return views;
    const users = ok(await dv.retrieveMultipleRecordsAsync<Row>(T.user, {
      filter: ids.map((id) => `systemuserid eq ${id}`).join(' or '), select: ['systemuserid', 'fullname'],
    })) as Row[];
    const nameById = new Map(users.map((u) => [(s(u, 'systemuserid') ?? '').toLowerCase(), s(u, 'fullname') ?? '']));
    return views.map((v) => {
      const name = nameById.get(v.creatorId.toLowerCase());
      return name ? { ...v, creatorName: name } : v;
    });
  }

  // Phase 3: server-side paged search via the SearchDocuments Custom API. Omitted filters aren't sent.
  async searchDocuments(query: DocumentQuery, cookie?: string): Promise<DocumentPage> {
    const d = ok(await Sanic_sigil_capi_SearchDocumentsService.sanic_sigil_capi_SearchDocuments({
      Text: query.text || undefined,
      CreatorId: query.creatorId || undefined,
      Status: query.status,
      ParticipantIds: query.participantIds?.length ? query.participantIds.join(',') : undefined,
      SignatureVersion: query.signatureVersion,
      Sort: query.sort,
      PageSize: query.pageSize,
      PagingCookie: cookie,
    })) as { ResultsJson?: string; Total?: number; NextPagingCookie?: string };
    const raw = JSON.parse(d.ResultsJson ?? '[]') as RawDoc[];
    return { rows: raw.map(mapRawDoc), total: d.Total ?? raw.length, nextCookie: d.NextPagingCookie ?? '' };
  }

  async myPending(): Promise<{ tx: TransactionView; participant: ParticipantView }[]> {
    const parts = ok(await dv.retrieveMultipleRecordsAsync<Row>(T.participant, {
      filter: `_${COL.pUserId}_value eq ${await this.me()} and ${COL.status} eq ${PARTICIPANT_ACTIVE_TURN}`,
    })) as Row[];
    const out: { tx: TransactionView; participant: ParticipantView }[] = [];
    for (const pr of parts) {
      const txId = lookup(pr, COL.pTransactionId);
      if (!txId) continue;
      const tx = await this.getTransaction(txId);
      if (tx && (tx.state === TX_PENDING || tx.state === TX_PARTIALLY_SIGNED)) {
        out.push({ tx, participant: partView(pr) });
      }
    }
    return out;
  }

  async getTransaction(txId: string): Promise<TransactionView | undefined> {
    const rows = ok(await dv.retrieveMultipleRecordsAsync<Row>(T.tx, { filter: `${COL.txId} eq ${txId}` })) as Row[];
    return rows[0] ? txView(rows[0]) : undefined;
  }

  async participantsOf(txId: string): Promise<ParticipantView[]> {
    const rows = ok(await dv.retrieveMultipleRecordsAsync<Row>(T.participant, {
      filter: `_${COL.pTransactionId}_value eq ${txId}`, orderBy: [`${COL.pOrder} asc`],
    })) as Row[];
    return rows.map(partView);
  }

  async zonesOf(txId: string): Promise<ZoneView[]> {
    // Zones link to a participant, which links to the transaction — resolve via the participants.
    const parts = await this.participantsOf(txId);
    if (!parts.length) return [];
    const filter = parts.map((p) => `_${COL.zParticipantId}_value eq ${p.id}`).join(' or ');
    const rows = ok(await dv.retrieveMultipleRecordsAsync<Row>(T.zone, { filter })) as Row[];
    return rows.map(zoneView);
  }

  async eventsOf(txId: string): Promise<EventView[]> {
    const rows = ok(await dv.retrieveMultipleRecordsAsync<Row>(T.event, {
      filter: `_${COL.pTransactionId}_value eq ${txId}`, orderBy: [`${COL.eOccurredOn} asc`],
    })) as Row[];
    return rows.map(eventView);
  }
}
