// REAL implementation of SigilApi over @microsoft/power-apps.
//
// Custom API calls → the TYPED CLIENTS generated by `power-apps add-dataverse-api` (src/generated/,
// autogenerated, do NOT edit). Each service exposes one static method whose positional parameters
// mirror the Custom API's request parameters and returns an IOperationResult ({ success, data, error }).
// Table reads → the Dataverse connector (MicrosoftDataverseService.ListRecords) with $filter or a
// FetchXML that uses `eq-userid` (server-side current user) so we don't resolve identity client-side.
//
// ⚠️ FIRST INTEGRATION PASS: the read mappings assume the standard entity-set names (logical name +
// "s") and Dataverse response shape (lookups as `_<attr>_value`, option sets as numbers, formatted
// values via the include-annotations prefer). Verify end-to-end with `power-apps run` against Dev.

import type {
  CreateTransactionInput,
  UpdateDraftInput,
  GetDocumentContentInput,
  RejectTransactionInput,
  CancelTransactionInput,
  ValidateMasterSignatureOutput,
  GetMasterSignatureOutput,
  VerifyDocumentInput,
  VerifyDocumentOutput,
} from './contracts';
import type {
  SigilApi,
  TransactionView,
  ParticipantView,
  EventView,
  ZoneView,
  UserSummary,
  MasterSignatureVersion,
} from './SigilApi';
import {
  Sanic_sigil_capi_CreateTransactionService,
  Sanic_sigil_capi_UpdateDraftService,
  Sanic_sigil_capi_DeleteDraftService,
  Sanic_sigil_capi_SendTransactionService,
  Sanic_sigil_capi_SubmitSignatureService,
  Sanic_sigil_capi_RejectTransactionService,
  Sanic_sigil_capi_CancelTransactionService,
  Sanic_sigil_capi_RetrySealingService,
  Sanic_sigil_capi_GetDocumentContentService,
  Sanic_sigil_capi_ValidateMasterSignatureService,
  Sanic_sigil_capi_GetMasterSignatureService,
  Sanic_sigil_capi_GetMasterSignatureHistoryService,
  Sanic_sigil_capi_VerifyDocumentService,
  MicrosoftDataverseService,
} from '../generated';

/** Unwraps a generated IOperationResult: returns the response body, or throws on failure. */
function ok(result: { success: boolean; data: unknown; error?: unknown }): unknown {
  if (!result.success) {
    throw result.error instanceof Error ? result.error : new Error('Dataverse operation failed.');
  }
  return result.data;
}

// ── Schema (doc 12). Entity SET names = logical name + "s"; primary keys = logical name + "id". ──
const SET = {
  tx: 'sanic_sigil_tbl_transactions',
  participant: 'sanic_sigil_tbl_participants',
  zone: 'sanic_sigil_tbl_signaturezones',
  event: 'sanic_sigil_tbl_events',
  user: 'systemusers',
} as const;
const LN = { participant: 'sanic_sigil_tbl_participant', zone: 'sanic_sigil_tbl_signaturezone' } as const;
const COL = {
  txId: 'sanic_sigil_tbl_transactionid',
  partId: 'sanic_sigil_tbl_participantid',
  zoneId: 'sanic_sigil_tbl_signaturezoneid',
  eventId: 'sanic_sigil_tbl_eventid',
  name: 'sanic_sigil_name',
  status: 'sanic_sigil_status',
  routing: 'sanic_sigil_routingtype',
  message: 'sanic_sigil_message',
  sentOn: 'sanic_sigil_senton',
  expiresOn: 'sanic_sigil_expireson',
  completedOn: 'sanic_sigil_completedon',
  pTransactionId: 'sanic_sigil_transactionid', // participant/event → transaction lookup
  pUserId: 'sanic_sigil_userid',
  pOrder: 'sanic_sigil_order',
  pTurnActivatedOn: 'sanic_sigil_turnactivatedon',
  pSignedOn: 'sanic_sigil_signedon',
  pSignerName: 'sanic_sigil_signername',
  pSignerEmail: 'sanic_sigil_signeremail',
  zParticipantId: 'sanic_sigil_participantid',
  zPage: 'sanic_sigil_page',
  zPosX: 'sanic_sigil_posx',
  zPosY: 'sanic_sigil_posy',
  zWidth: 'sanic_sigil_width',
  zHeight: 'sanic_sigil_height',
  eType: 'sanic_sigil_type',
  eActorName: 'sanic_sigil_actorname',
  eOccurredOn: 'sanic_sigil_occurredon',
  eDetails: 'sanic_sigil_details',
  owner: '_ownerid_value',
} as const;

const PARTICIPANT_ACTIVE_TURN = 159460001;
const TX_PENDING = 159460001;
const TX_PARTIALLY_SIGNED = 159460002;
const ROUTING_SEQUENTIAL = 159460000;

type Row = Record<string, unknown>;
const s = (r: Row, k: string): string | undefined => (r[k] == null ? undefined : String(r[k]));
const n = (r: Row, k: string): number | undefined => (r[k] == null ? undefined : Number(r[k]));
const fmt = (r: Row, k: string): string | undefined => s(r, `${k}@OData.Community.Display.V1.FormattedValue`);
const lookup = (r: Row, attr: string): string | undefined => s(r, `_${attr}_value`);
const esc = (v: string): string => v.replace(/'/g, "''"); // OData string literal escaping

function txView(r: Row): TransactionView {
  return {
    id: s(r, COL.txId) ?? '',
    name: s(r, COL.name) ?? '',
    state: n(r, COL.status) ?? 0,
    routing: n(r, COL.routing) === ROUTING_SEQUENTIAL ? 'sequential' : 'parallel',
    creatorId: s(r, COL.owner) ?? '',
    creatorName: fmt(r, 'ownerid'),
    message: s(r, COL.message),
    sentOn: s(r, COL.sentOn),
    expiresOn: s(r, COL.expiresOn),
    completedOn: s(r, COL.completedOn),
  };
}
function partView(r: Row): ParticipantView {
  return {
    id: s(r, COL.partId) ?? '',
    userId: lookup(r, COL.pUserId) ?? '',
    name: s(r, COL.pSignerName) ?? fmt(r, COL.pUserId),
    email: s(r, COL.pSignerEmail),
    order: n(r, COL.pOrder),
    state: n(r, COL.status) ?? 0,
    signedOn: s(r, COL.pSignedOn),
    turnActivatedOn: s(r, COL.pTurnActivatedOn),
  };
}
function eventView(r: Row): EventView {
  return {
    id: s(r, COL.eventId) ?? '',
    type: n(r, COL.eType) ?? 0,
    actorName: s(r, COL.eActorName),
    occurredOn: s(r, COL.eOccurredOn) ?? s(r, 'createdon') ?? '',
    details: s(r, COL.eDetails),
  };
}
function zoneView(r: Row): ZoneView {
  return {
    id: s(r, COL.zoneId) ?? '',
    participantId: lookup(r, COL.zParticipantId) ?? '',
    page: n(r, COL.zPage) ?? 1,
    x: n(r, COL.zPosX) ?? 0,
    y: n(r, COL.zPosY) ?? 0,
    w: n(r, COL.zWidth) ?? 0,
    h: n(r, COL.zHeight) ?? 0,
  };
}
function userView(r: Row): UserSummary {
  return { id: s(r, 'systemuserid') ?? '', name: s(r, 'fullname') ?? '', email: s(r, 'internalemailaddress') };
}

export class PowerAppsSigilApi implements SigilApi {
  // Identity is NOT taken from here: the app shell resolves getContext() (async) ONCE at startup and
  // provides it via PowerProvider (doc 05 §9). This exists for the seam contract only.
  currentUser() {
    return {};
  }

  // ── Custom API actions ──
  async validateMasterSignature(imageBase64: string): Promise<ValidateMasterSignatureOutput> {
    return ok(
      await Sanic_sigil_capi_ValidateMasterSignatureService.sanic_sigil_capi_ValidateMasterSignature(imageBase64),
    ) as ValidateMasterSignatureOutput;
  }
  async getMasterSignature(): Promise<GetMasterSignatureOutput> {
    return ok(
      await Sanic_sigil_capi_GetMasterSignatureService.sanic_sigil_capi_GetMasterSignature(),
    ) as GetMasterSignatureOutput;
  }
  async getMasterSignatureHistory(): Promise<MasterSignatureVersion[]> {
    const d = ok(
      await Sanic_sigil_capi_GetMasterSignatureHistoryService.sanic_sigil_capi_GetMasterSignatureHistory(),
    ) as { HistoryJson: string };
    return JSON.parse(d.HistoryJson) as MasterSignatureVersion[];
  }
  async createTransaction(input: CreateTransactionInput): Promise<string> {
    const d = ok(
      await Sanic_sigil_capi_CreateTransactionService.sanic_sigil_capi_CreateTransaction(
        input.Name, input.RoutingType, input.PdfBase64, input.ParticipantsJson,
        input.Message, input.ExpirationDays, input.ZonesJson,
      ),
    ) as { TransactionId: string };
    return d.TransactionId;
  }
  async updateDraft(input: UpdateDraftInput): Promise<void> {
    ok(
      await Sanic_sigil_capi_UpdateDraftService.sanic_sigil_capi_UpdateDraft(
        input.Target, input.Name, input.Message, input.RoutingType,
        input.ExpirationDays, input.PdfBase64, input.ParticipantsJson, input.ZonesJson,
      ),
    );
  }
  async deleteDraft(txId: string): Promise<void> {
    ok(await Sanic_sigil_capi_DeleteDraftService.sanic_sigil_capi_DeleteDraft(txId));
  }
  async sendTransaction(txId: string): Promise<void> {
    ok(await Sanic_sigil_capi_SendTransactionService.sanic_sigil_capi_SendTransaction(txId));
  }
  async submitSignature(txId: string): Promise<boolean> {
    const d = ok(
      await Sanic_sigil_capi_SubmitSignatureService.sanic_sigil_capi_SubmitSignature(txId),
    ) as { IsLastSigner: boolean };
    return d.IsLastSigner;
  }
  async rejectTransaction(input: RejectTransactionInput): Promise<void> {
    ok(await Sanic_sigil_capi_RejectTransactionService.sanic_sigil_capi_RejectTransaction(input.Target, input.Reason));
  }
  async cancelTransaction(input: CancelTransactionInput): Promise<void> {
    ok(await Sanic_sigil_capi_CancelTransactionService.sanic_sigil_capi_CancelTransaction(input.Target, input.Reason));
  }
  async retrySealing(txId: string): Promise<void> {
    ok(await Sanic_sigil_capi_RetrySealingService.sanic_sigil_capi_RetrySealing(txId));
  }
  async getDocumentContent(input: GetDocumentContentInput): Promise<string> {
    const d = ok(
      await Sanic_sigil_capi_GetDocumentContentService.sanic_sigil_capi_GetDocumentContent(input.Target, input.DocumentType),
    ) as { PdfBase64: string };
    return d.PdfBase64;
  }
  async verifyDocument(input: VerifyDocumentInput): Promise<VerifyDocumentOutput> {
    return ok(
      await Sanic_sigil_capi_VerifyDocumentService.sanic_sigil_capi_VerifyDocument(input.TransactionId, input.Sha256Hash),
    ) as VerifyDocumentOutput;
  }

  // ── Table reads (Dataverse connector) ──
  /** ListRecords → the rows array. `include-annotations` brings FormattedValue for lookups/choices. */
  private async rows(
    entitySet: string,
    opts: { select?: string; filter?: string; orderby?: string; fetchXml?: string },
  ): Promise<Row[]> {
    const out = ok(
      await MicrosoftDataverseService.ListRecords(
        entitySet,
        'odata.include-annotations="OData.Community.Display.V1.FormattedValue"',
        undefined, undefined,
        opts.select, opts.filter, opts.orderby, undefined, opts.fetchXml,
      ),
    ) as { value?: Row[] };
    return out.value ?? [];
  }

  async searchUsers(query: string): Promise<UserSummary[]> {
    const q = query.trim();
    const base = `isdisabled eq false`;
    const filter = q
      ? `(contains(fullname,'${esc(q)}') or contains(internalemailaddress,'${esc(q)}')) and ${base}`
      : base;
    const rows = await this.rows(SET.user, {
      select: 'systemuserid,fullname,internalemailaddress',
      filter,
      orderby: 'fullname asc',
    });
    return rows.slice(0, 20).map(userView);
  }

  async myRequests(): Promise<TransactionView[]> {
    // Transactions I created (owner == current user).
    const rows = await this.rows(SET.tx, {
      fetchXml:
        `<fetch><entity name="sanic_sigil_tbl_transaction"><all-attributes/>` +
        `<filter><condition attribute="ownerid" operator="eq-userid"/></filter>` +
        `<order attribute="createdon" descending="true"/></entity></fetch>`,
    });
    return rows.map(txView);
  }

  async myParticipations(): Promise<TransactionView[]> {
    // Transactions where I'm a participant (link participant → transaction, participant.user == me).
    const rows = await this.rows(SET.tx, {
      fetchXml:
        `<fetch><entity name="sanic_sigil_tbl_transaction"><all-attributes/>` +
        `<link-entity name="${LN.participant}" from="${COL.pTransactionId}" to="${COL.txId}" intersect="true">` +
        `<filter><condition attribute="${COL.pUserId}" operator="eq-userid"/></filter></link-entity>` +
        `<order attribute="createdon" descending="true"/></entity></fetch>`,
    });
    return rows.map(txView);
  }

  async myPending(): Promise<{ tx: TransactionView; participant: ParticipantView }[]> {
    // My participant rows on my active turn; keep those whose tx is pending / partially signed.
    const parts = await this.rows(SET.participant, {
      fetchXml:
        `<fetch><entity name="${LN.participant}"><all-attributes/><filter>` +
        `<condition attribute="${COL.pUserId}" operator="eq-userid"/>` +
        `<condition attribute="${COL.status}" operator="eq" value="${PARTICIPANT_ACTIVE_TURN}"/>` +
        `</filter></entity></fetch>`,
    });
    const out: { tx: TransactionView; participant: ParticipantView }[] = [];
    for (const pr of parts) {
      const txId = lookup(pr, COL.pTransactionId);
      if (!txId) continue;
      const tx = await this.getTransaction(txId);
      if (tx && (tx.state === TX_PENDING || tx.state === TX_PARTIALLY_SIGNED)) {
        out.push({ tx, participant: partView(pr) });
      }
    }
    return out;
  }

  async getTransaction(txId: string): Promise<TransactionView | undefined> {
    const rows = await this.rows(SET.tx, { filter: `${COL.txId} eq ${txId}` });
    return rows[0] ? txView(rows[0]) : undefined;
  }

  async participantsOf(txId: string): Promise<ParticipantView[]> {
    const rows = await this.rows(SET.participant, {
      filter: `_${COL.pTransactionId}_value eq ${txId}`,
      orderby: `${COL.pOrder} asc`,
    });
    return rows.map(partView);
  }

  async zonesOf(txId: string): Promise<ZoneView[]> {
    // Zones link to a participant, which links to the transaction — join through participant.
    const rows = await this.rows(SET.zone, {
      fetchXml:
        `<fetch><entity name="${LN.zone}"><all-attributes/>` +
        `<link-entity name="${LN.participant}" from="${COL.partId}" to="${COL.zParticipantId}">` +
        `<filter><condition attribute="${COL.pTransactionId}" operator="eq" value="${txId}"/></filter>` +
        `</link-entity></entity></fetch>`,
    });
    return rows.map(zoneView);
  }

  async eventsOf(txId: string): Promise<EventView[]> {
    const rows = await this.rows(SET.event, {
      filter: `_${COL.pTransactionId}_value eq ${txId}`,
      orderby: `${COL.eOccurredOn} asc`,
    });
    return rows.map(eventView);
  }
}
